### ISSUE TITLE
no output on MacOs

### ISSUE THREAD

**Issue by AshtonSBradley** [piever/InteractBase.jl#60] opened 2018-07-23 00:20 UTC
when trying one of the docs examples
```julia
using InteractBase, InteractUIkit, WebIO

width, height = 700, 300
colors = ["black", "gray", "silver", "maroon", "red", "olive", "yellow", "green", "lime", "teal", "aqua", "navy", "blue", "purple", "fuchsia"]
color(i) = colors[i%length(colors)+1]
ui = @manipulate for nsamples in 1:200,
        sample_step in slider(0.01:0.01:1.0, value=0.1, label="sample step"),
        phase in slider(0:0.1:2pi, value=0.0, label="phase"),
        radii in 0.1:0.1:60
    cxs_unscaled = [i*sample_step + phase for i in 1:nsamples]
    cys = sin.(cxs_unscaled) .* height/3 .+ height/2
    cxs = cxs_unscaled .* width/4pi
    dom"svg:svg[width=$width, height=$height]"(
        (dom"svg:circle[cx=$(cxs[i]), cy=$(cys[i]), r=$radii, fill=$(color(i))]"()
            for i in 1:nsamples)...
    )
end
display(ui)
```
the result is that it runs without error, but there is no output. The widget does not materialize.

```julia
julia> versioninfo()
Julia Version 0.6.4
Commit 9d11f62bcb (2018-07-09 19:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=16)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by piever** [comment] 2018-07-23 08:49
Just to make sure, you're running this in a Jupyter notebook?

To figure out where the problem is, you could try `Pkg.update(); Pkg.build("WebIO")` (WebIO is the package that actually turns Juila code into HTML to add in the page) and then running some code that only relies on WebIO. For example, does:

```julia
using WebIO
display(Node(:input, attributes = Dict("type" => "range")))
```

work for you?

**Comment by AshtonSBradley** [comment] 2018-07-23 20:24
Thanks for your help - no, slider does not appear. 

Should I move this to WebIO?

**Comment by piever** [comment] 2018-07-23 20:38
Yes, if it can be reproduced with only WebIO it's definitely a WebIO issue (I'll close this one here).

In the issue there make sure to include the output of `Pkg.status("WebIO")`and what browser you're using (I wonder whether Safari could be problematic, I've never tested it).

It would also help to debug if you could include what you see if you right click in the notebook in the space where the output should be and do "inspect element". You can also open the browser console (Cmd + Opt + J in MacOS I believe) and see if there are any errors there.

**Closed by piever** 2018-07-23 20:38 UTC
